theme = "sonokai_custom"

# =================================================EDITOR CONFIGS===================================================
[editor]
line-number = "relative"
cursorline = true
clipboard-provider = "pasteboard"

[editor.lsp]
auto-signature-help = false
display-inlay-hints = true
display-progress-messages = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "|"
skip-levels = 1

# =================================================KEYMAP CONFIGS===================================================
[keys.normal]
C-g = ":sh wezterm cli split-pane -- lazygit"
C-o = ":open ~/.config/helix/config.toml"
C-j = "move_line_down"
C-k = "move_line_up"
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"

[keys.select]
C-j = "move_line_down"
C-k = "move_line_up"

[keys.insert]
C-j = "move_line_down"
C-k = "move_line_up"

[keys.insert.k]
j = "normal_mode"
