theme = "sonokai_custom"

# =================================================EDITOR CONFIGS===================================================
[editor]
line-number = "relative"
cursorline = true
clipboard-provider = "pasteboard"
scrolloff = 10
completion-trigger-len = 1
completion-replace = true
bufferline = "multiple"
popup-border = "all"

[editor.lsp]
auto-signature-help = false
display-inlay-hints = true
display-progress-messages = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "|"
skip-levels = 1

[editor.inline-diagnostics]
cursor-line = "hint"
# other-lines = "warning"

[editor.auto-save]
focus-lost = true
after-delay.enable = true
after-delay.timeout = 10_000

[editor.statusline]
left = [
  "mode",
  "file-name",
  "file-modification-indicator",
  "register",
  "spinner",
]
right = [
  "diagnostics",
  "version-control",
  "selections",
  "position",
  "file-encoding",
  "file-line-ending",
  "total-line-numbers",
  "file-type",
]
separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
diagnostics = ["warning", "error"]
workspace-diagnostics = ["warning", "error"]

# =================================================KEYMAP CONFIGS===================================================
[keys.normal]
C-l = ":sh wezterm cli split-pane --percent 70 -- lazygit > /dev/null 2>&1"
C-o = ":open ~/.config/helix/config.toml"
C-j = "move_line_down"
C-k = "move_line_up"
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"

[keys.select]
C-j = "move_line_down"
C-k = "move_line_up"
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"

[keys.insert]
C-j = "move_line_down"
C-k = "move_line_up"

[keys.insert.k]
j = "normal_mode"
